action 수정 1. 현재 jar를 통째로 복사해서 plain jar와 실제 실행해야 하는 jar가 같이올라감(그로인해 Docker가 어떤 것을 복사해야 할 지 몰라 build를 실패시킴 > 이전에 성공했던 이미지를 불러와서 빌드시킴) 2. 실행 가능한 jar만 하나 찾고 그 파일을 명시적으로 옮기기(현재는 *.jar하는데 이걸 변경함)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,10 +32,19 @@ jobs:
             ls -al
             echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > private_key.pem
             chmod 600 private_key.pem
+            # build/libs에서 실행 가능한 하나의 .jar 파일 이름만 찾기
+            # (-plain.jar 같은 파일을 제외합니다)
+            JAR_FILE=$(find $GITHUB_WORKSPACE/build/libs -name "*.jar" ! -name "*-plain.jar" | head -n 1)
+            
+            if [ -z "$JAR_FILE" ]; then
+              echo "ERROR: No executable .jar file found."
+              exit 1
+            fi
+            echo "Found .jar file: $JAR_FILE"
             # 이전 .jar 먼저 삭제
             ssh -o StrictHostKeyChecking=no -i private_key.pem -p 2222 ubuntukjy@${{ secrets.HOST_IP }} 'rm -f /spring/docker/compose/authinformation/jar/*.jar'
             # 새로운 .jar 복사
-            scp -o StrictHostKeyChecking=no -i private_key.pem -P 2222 $GITHUB_WORKSPACE/build/libs/*.jar ubuntukjy@${{ secrets.HOST_IP }}:/spring/docker/compose/authinformation/jar
+            scp -o StrictHostKeyChecking=no -i private_key.pem -P 2222 &JAR_FILE ubuntukjy@${{ secrets.HOST_IP }}:/spring/docker/compose/authinformation/jar
             
       - name: Set SSH ssh-action
         uses: appleboy/ssh-action@master
